/*
 * This source file was generated by the Gradle 'init' task
 */
package mcdonald;

import mcdonald.view.Window;

public class Main {
    public static void main(String[] args) {
        new Window().display();
    }
    
}
