/*
 * This source file was generated by the Gradle 'init' task
 */
package mcdonald;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
    
}
